# Generated by Django 3.1.7 on 2021-03-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210324_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='response',
        ),
    ]
